# Generated by Django 5.0.2 on 2026-05-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='clave_maestro',
            new_name='id_trabajador',
        ),
    ]
