# Generated by Django 5.0.2 on 2026-05-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0002_rename_clave_maestro_maestros_id_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='grado_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='sueldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
