# Generated by Django 5.0.2 on 2026-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0003_administradores_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
